context:
  name: cryspy
  version: "0.9.0"
  python_min: "3.9" # https://github.com/prefix-dev/rattler-build/pull/1122

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cryspy-${{ version }}.tar.gz
  sha256: f2882de819fb76eb988ef3a4a3447a7f4ba5e7d45f2fed577102502ea011c271

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy
    - scipy
    - pycifstar
    - matplotlib-base

tests:
  - script: python -c "import cryspy"
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: PNPD data analysis
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ikibalin/cryspy

extra:
  recipe-maintainers:
    - MridulS
